// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimateController from "./animate_controller"
application.register("animate", AnimateController)


import SliderController from "./slider_controller"
application.register("slider", SliderController)

import ScrollIdController from "./scroll_id_controller"
application.register("scrollId", ScrollIdController)
