// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimateController from "./animate_controller"
application.register("animate", AnimateController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import ParishMapController from "./parish_map_controller"
application.register("parish-map", ParishMapController)

import ReceptionMapController from "./reception_map_controller"
application.register("reception-map", ReceptionMapController)

import GalleryController from "./gallery_controller"
application.register("gallery", GalleryController)
